package quarry

import (
	"bytes"
	"encoding/json"
	"fmt"
	"unicode/utf8"
)

// StreamExpectation is the conformance expectation a host checks its reading of an event
// stream against (#9). Paired with the streams in testdata/runevents/ and regenerated by
// runevent_corpus_test.go.
//
// WHY AN EXPECTATION AND NOT JUST THE STREAM. A `.ndjson` alone leaves each host
// encoding its own reading of the contract in its own native types, and two
// implementations can then both "pass" the same fixture while disagreeing about what it
// means — which is the exact failure the corpus exists to make impossible. bucktooth (Go)
// and rustynail (Rust) are two independent readers of one contract; the expectation is
// the third artifact that makes them comparable.
//
// WHY IT LIVES IN THE ROOT PACKAGE AND NOT IN A _test.go FILE. A type only a test can
// construct cannot be the thing a host vendors: the twins import quarry, so the schema
// they decode into has to be importable. It is also the reason this is a value type with
// a pure builder — the expectation must be a deterministic function of the record, or
// regenerating the corpus produces a diff for no reason (P8).
//
// EVERY FIGURE THAT CAME FROM MONEY IS AN INTEGER. The stream prices in USD floats
// because agate does; the expectation must not, or a host could pass by reproducing
// quarry's float arithmetic instead of its ledger. Per-row cost_micros and total_micros
// are the ledger's own values, and the host's check is parse-float → round(×1e6) →
// compare (#18, docs/integration-requirements.md §3).
type StreamExpectation struct {
	// Case is the fixture's name, matching the .ndjson basename.
	Case string `json:"case"`
	// Note says what this case is FOR — which is load-bearing rather than commentary. A
	// fixture whose purpose is undocumented gets "fixed" by the next person who finds it
	// surprising, and the surprising ones here are surprising on purpose.
	Note string `json:"note"`

	// StreamVersion and Producer are read off the frame (D2). A host must refuse a
	// version it does not know, so the expectation states what the frame said rather
	// than assuming the current constant.
	StreamVersion int    `json:"stream_version"`
	Producer      string `json:"producer"`

	// EventTypes is the ordered type discriminants, so a host can check it folded the
	// stream in order — agate's SPA reducer is order-dependent, and the artifact must
	// close the agate-visible part of the run.
	EventTypes []string `json:"event_types"`

	// ExitCode is what `quarry run` returned for this shape (D4). Part of the
	// expectation and not merely of the README: a host branches on it, and the mapping
	// from outcome to code is exactly what two implementations could read differently.
	ExitCode int `json:"exit_code"`

	// Outcome, BoundBy, Gaps and Unfunded restate the terminal event. GAPS AND UNFUNDED
	// ARE SEPARATE FIELDS BECAUSE THEY ARE SEPARATE FACTS: under the standing ruling only
	// TIME produces a gap, and a host that summed them would report a run bound by money
	// as one bound by time. A single "incomplete" count would be the flattening §8
	// forbids.
	Outcome  Outcome      `json:"outcome"`
	BoundBy  Denomination `json:"bound_by"`
	Gaps     int          `json:"gaps"`
	Unfunded int          `json:"unfunded"`

	// TotalMicros is the ledger's spend; CapMicros the contract it sat under, -1 for
	// Unlimited (P4).
	TotalMicros int64 `json:"total_micros"`
	CapMicros   int64 `json:"cap_micros"`

	// Receipt is the itemisation, in micro-units, plus whether it reconciles.
	Receipt ReceiptExpectation `json:"receipt"`

	// ModelSpendMicros is Σ ModelEvent.Cost converted back to micro-units, and
	// ModelSpendUnexplainedMicros is the residual against the receipt total.
	//
	// STATED EXPLICITLY RATHER THAN LEFT DERIVABLE, because on a real partition run the
	// residual is NOT ZERO — a reduce node spends with no ModelVersion, so it is itemised
	// in the receipt and absent from every model event (see the ModelEvent doc, and
	// live-partition.json where the residual is over half the run). A host rendering
	// "spend by model" beside a total will show two numbers that do not tie; without this
	// field each twin would independently decide whether that is a bug, and one of them
	// would "fix" it by inventing an untagged row.
	ModelSpendMicros            int64 `json:"model_spend_micros"`
	ModelSpendUnexplainedMicros int64 `json:"model_spend_unexplained_micros"`

	// ProvenancePresent is a THREE-STATE COLLAPSED DELIBERATELY TO TWO, and the comment
	// is here because the collapse is the point. agate's stability is a non-nullable
	// float, so quarry says "unmeasured" by omitting the whole provenance object (D3).
	// A host must therefore read absent as UNMEASURED and never as zero — false here
	// means "quarry declined to publish an estimate", not "stability was 0".
	ProvenancePresent bool `json:"provenance_present"`

	// AnswerPresent and AnswerRunes describe the answer without embedding it: the text is
	// already in the .ndjson, and duplicating it would make the expectation a second
	// place for it to drift. RUNES, not bytes — a host that measured bytes would report a
	// length no other implementation agrees with (unicode.json exists for this).
	AnswerPresent bool `json:"answer_present"`
	AnswerRunes   int  `json:"answer_runes"`
}

// ReceiptExpectation is the receipt in the ledger's own integers.
type ReceiptExpectation struct {
	Rows        []ReceiptRowExpectation `json:"rows"`
	TotalMicros int64                   `json:"total_micros"`
	// Reconciles is Σ round(row × 1e6) == round(total × 1e6). Always true for a stream
	// quarry produced — it is asserted, not reported — and carried anyway so a host can
	// check its own comparison against a case where the float sum DISAGREES. On
	// live-partition.json it does, by 1.4e-17 (#18).
	Reconciles bool `json:"reconciles"`
	// FloatSumEqualsTotal records whether the NAIVE float sum happens to agree. False is
	// the interesting value: it means this fixture would catch a host that summed floats,
	// which is what makes it worth vendoring. A corpus of only-true cases would pass a
	// broken reader.
	FloatSumEqualsTotal bool `json:"float_sum_equals_total"`
}

// ReceiptRowExpectation is one line, priced in micro-units.
type ReceiptRowExpectation struct {
	Label      string `json:"label"`
	Kind       string `json:"kind"`
	CostMicros int64  `json:"cost_micros"`
	// Cost is the float AS EMITTED, kept beside the integer so the fixture pins the
	// conversion rather than only its result.
	//
	// TWO SHAPES A HOST MUST ACCEPT, both verified against Go's encoder rather than
	// assumed. Go's encoding/json avoids exponent notation on [1e-6, 1e21), and one
	// micro-unit IS 1e-6, so no cost quarry can emit ever appears as 7.6e-05 — a first
	// draft of this comment claimed it did. What DOES happen is the other end: a round
	// dollar serializes with no decimal point at all, so a $1.00 row reads `"cost":1`.
	// A host whose parser demands a decimal point rejects a valid receipt, and the
	// cheapest row is the one most likely to be round.
	Cost float64 `json:"cost"`
}

// ExpectationOf derives the conformance expectation from a stream (#9).
//
// TAKES THE EVENTS AND NOT THE RECORD, so the expectation describes the bytes a host will
// actually read. Deriving any field from the record instead would let the expectation and
// the stream drift apart while both looked self-consistent — the corpus would then verify
// quarry against itself twice and the host against nothing. Every figure here therefore
// comes back OFF THE WIRE, including the ones the record could answer directly: total
// spend is read from the outcome event, not from r.TotalCost().
func ExpectationOf(name, note string, exitCode int, events []RunEvent) StreamExpectation {
	e := StreamExpectation{
		Case:     name,
		Note:     note,
		ExitCode: exitCode,
	}
	var modelSum Units
	var receipt ReceiptEvent
	for _, ev := range events {
		e.EventTypes = append(e.EventTypes, ev.eventType())
		switch v := ev.(type) {
		case StreamEvent:
			e.StreamVersion, e.Producer = v.Version, v.Producer
		case ModelEvent:
			modelSum += USDToUnits(v.Cost)
		case AnswerEvent:
			e.AnswerPresent = true
			e.AnswerRunes = utf8.RuneCountInString(v.Text)
		case ReceiptEvent:
			receipt = v
		case ArtifactEvent:
			e.ProvenancePresent = v.Provenance != nil
		case OutcomeEvent:
			e.Outcome, e.BoundBy = v.Outcome, v.BoundBy
			e.Gaps, e.Unfunded = v.Gaps, v.Unfunded
			e.TotalMicros, e.CapMicros = v.TotalMicros, v.CapMicros
		}
	}

	var naive float64
	rows := make([]ReceiptRowExpectation, 0, len(receipt.Rows))
	for _, row := range receipt.Rows {
		naive += row.Cost
		rows = append(rows, ReceiptRowExpectation{
			Label: row.Label, Kind: row.Kind,
			CostMicros: int64(USDToUnits(row.Cost)), Cost: row.Cost,
		})
	}
	e.Receipt = ReceiptExpectation{
		Rows:                rows,
		TotalMicros:         int64(USDToUnits(receipt.Total)),
		Reconciles:          ReceiptReconciles(receipt),
		FloatSumEqualsTotal: naive == receipt.Total,
	}
	e.ModelSpendMicros = int64(modelSum)
	e.ModelSpendUnexplainedMicros = int64(USDToUnits(receipt.Total) - modelSum)
	return e
}

// WriteExpectation encodes an expectation as the corpus file a host vendors.
//
// INDENTED, unlike the record's canonical encoding, and the difference is deliberate:
// this is not a hashed artifact, it is a file two other repos read and diff. Its
// determinism comes from the fold being pure, not from the encoding being compact.
//
// Trailing newline so the file is a well-formed text file and a diff of the last line is
// legible — json.Encoder adds it.
func WriteExpectation(exp StreamExpectation) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	// Off for the same reason WriteRunEvents has it off: an escaped ampersand in a receipt
	// label would make the expectation's label differ from the stream's for no reason.
	enc.SetEscapeHTML(false)
	if err := enc.Encode(exp); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// ReadStreamEvents parses an NDJSON stream the way a HOST does — as untyped objects
// keyed by `type`, tolerating kinds it does not know (#9's unknown-kind case).
//
// DELIBERATELY NOT THE TYPED UNION. runevent.go:41 claims "adding an event kind here
// cannot break an existing consumer" and nothing tested it; a parser that decoded into
// the closed set of Go types would prove the opposite of what the claim needs, because it
// would either reject the unknown kind or silently drop it without saying which. This
// returns every object with its type, so a caller can assert that the known kinds still
// fold correctly WITH an unknown one interleaved.
//
// A line with no `type` is an ERROR, not an ignorable object: `type` is the discriminant
// the whole union rests on, and a host that skipped such a line would be guessing.
// Likewise a trailing partial line — which is how a CRASHED run presents (D4), so
// reporting it rather than silently accepting it is the behaviour the corpus pins.
func ReadStreamEvents(data []byte) ([]map[string]any, error) {
	// SplitAfter, not Split: keeping the delimiter is what lets the last element say
	// whether the stream was \n-terminated. A crashed producer's final line is truncated,
	// and that is precisely the signal a host needs (see WriteRunEvents).
	var out []map[string]any
	for i, line := range bytes.SplitAfter(data, []byte("\n")) {
		if len(line) == 0 {
			continue // the empty tail after a terminating newline
		}
		if !bytes.HasSuffix(line, []byte("\n")) {
			return out, fmt.Errorf("line %d is not newline-terminated: the stream was truncated, "+
				"which means the producer did not finish (#9 D4)", i+1)
		}
		var obj map[string]any
		if err := json.Unmarshal(line, &obj); err != nil {
			return out, fmt.Errorf("line %d is not a JSON object: %w", i+1, err)
		}
		if _, ok := obj["type"].(string); !ok {
			return out, fmt.Errorf("line %d carries no string `type`: the discriminant the "+
				"whole union rests on is missing, so a consumer would be guessing", i+1)
		}
		out = append(out, obj)
	}
	return out, nil
}

// TerminalOutcome reads the outcome off a host stream, reporting whether it was there
// at all.
//
// THE FALSE CASE IS THE USEFUL ONE. A stream with no terminal event is a run that did
// not finish — killed, panicked, or cut off mid-write — and NDJSON cannot say so by
// itself, since a truncated stream yields whole lines up to the break. #9 requires a
// crashed run to be distinguishable from a time-truncated one, and this is the
// distinction: time truncation is an outcome the run REPORTS, a crash is the absence of
// any report. A host that defaulted the missing case to "complete" would build on an
// answer that was never finished.
//
// It scans rather than taking the last line, because the outcome's POSITION is not the
// contract — a future minor version may add a kind after it (D2's compatibility rule),
// and a reader keyed on "last line" would break on an addition the rule says is safe.
func TerminalOutcome(events []map[string]any) (Outcome, bool) {
	for i := len(events) - 1; i >= 0; i-- {
		if events[i]["type"] == "quarry_outcome" {
			s, ok := events[i]["outcome"].(string)
			return Outcome(s), ok
		}
	}
	return "", false
}
