package quarry

import (
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"unicode/utf8"
)

// The HOST CONFORMANCE CORPUS (#9): testdata/runevents/ holds a record per case, the
// NDJSON stream folded from it, and a language-neutral expectation the twins check their
// own readers against.
//
// TWO HALVES, AND THE SPLIT IS THE DESIGN. The records are CAPTURED — checked in, never
// regenerated — and the streams and expectations are DERIVED, regenerated by this test
// and asserted byte-identical. #9 asked for a script that produces the corpus under
// --fake, and half of that is not achievable; saying which half is the honest version:
//
//   - THE BUDGET-DEGRADED CASE IS UNREACHABLE UNDER --fake AT ALL. The fake's per-call
//     cost is uniform, so affordability funds every child or declines the split; a tree
//     with SOME children priced out does not exist in that mode (docs/design.md §13).
//     live-partition.json is a real Bedrock run, and it is also the only case whose
//     receipt rows fail to sum in float64 (#18) and the only one with a model-spend
//     residual. Three of the corpus's most load-bearing properties live in the one file
//     --fake cannot produce.
//   - THE TIME-TRUNCATED CASES ARE RACES. Their shape depends on how many fake calls
//     finished before a wall-clock deadline, so `--deadline 620ms` yields 3 gaps on this
//     machine and could yield 2 or 4 on another. Re-running them in CI would produce a
//     corpus that drifts, and #9 is explicit that a fixture drifting silently is worse
//     than none.
//
// So determinism is claimed for the FOLD, which is pure, and not for the runs. The
// records' provenance is in testdata/runevents/README.md: the exact invocation and the
// commit, so a human can reproduce a case deliberately even though CI must not.
//
// Regenerate with:
//
//	go test -run TestHostCorpus -update
var update = flag.Bool("update", false,
	"rewrite testdata/runevents/*.ndjson and *.expected.json from the checked-in records")

const corpusDir = "testdata/runevents"

// corpusCase pairs a checked-in record with what it is FOR and the exit code the CLI
// returned for it.
//
// The exit code is stated here rather than computed, and that is deliberate: computing it
// from the record would make this test assert that quarry agrees with itself. These are
// the codes the BINARY actually returned when the records were captured (see the README),
// so a change to cmd/quarry's mapping that contradicts them shows up as a diff.
type corpusCase struct {
	name     string
	note     string
	exitCode int
}

var corpusCases = []corpusCase{
	{
		name: "complete",
		note: "A run that finished inside its caps. The baseline every host should fold " +
			"correctly before looking at anything else.",
		exitCode: 0,
	},
	{
		name: "live-partition",
		note: "A REAL Bedrock run, 30 nodes / 25 receipt rows, and the most load-bearing " +
			"fixture here. Three things only it has: rows that do NOT sum to the total in " +
			"float64 (so a host summing floats fails on it — see #18); a model-spend " +
			"residual, because reduce nodes spend with no model version; and 5 unfunded " +
			"nodes, the cap-bound degradation that --fake cannot construct because its " +
			"per-call cost is uniform. Exit 0: degradation is not a failure.",
		exitCode: 0,
	},
	{
		name: "time-truncated",
		note: "A deadline cut this run short: it has GAPS and a partial answer. Exit 3, " +
			"distinct from complete — a host must be able to tell a partial answer from a " +
			"whole one without parsing prose. Gaps are TIME only; compare no-answer-spend.",
		exitCode: 3,
	},
	{
		name: "no-answer-time",
		note: "Every node gapped, so there is no answer at all. Classified no-answer rather " +
			"than time-truncated even though bound_by is latency: a host told to extend " +
			"this would be extending nothing. Note gaps=4 with total_micros=0 — the " +
			"deadline bit before anything was spent.",
		exitCode: 4,
	},
	{
		name: "no-answer-spend",
		note: "The spend counterpart: a cap below the floor priced out the root itself. " +
			"ZERO GAPS, one unfunded node — the distinction the record refuses to blur, " +
			"since only TIME produces a gap. A host that summed gaps and unfunded would " +
			"report this as time pressure and offer more of the wrong denomination.",
		exitCode: 4,
	},
	{
		name: "unicode",
		note: "Accents, an em-dash, CJK and a fullwidth question mark in the statement and " +
			"the answer. answer_runes counts RUNES, so a host measuring bytes disagrees " +
			"here and nowhere else. Also pins that HTML escaping is off.",
		exitCode: 0,
	},
	{
		name: "deadline-only",
		note: "A run with NO SPEND CAP, bound by a deadline it finished inside. The only case " +
			"where cap_micros is -1, and it exists because the README stated that rule with " +
			"no fixture behind it — a rule the corpus asserts and never exhibits is the kind " +
			"of requirement a host implements from prose and gets wrong. -1 and NOT 0: zero " +
			"reads as a cap of nothing, which would make this run — 251 micro-units against " +
			"a cap of 0 — look like an infinite overspend rather than an unlimited budget. " +
			"Absence is not zero (§8), at the wire.",
		exitCode: 0,
	},
	{
		name: "unicode-long",
		note: "The unicode case past the TRUNCATION boundary, which the short one cannot " +
			"reach. Receipt labels are cut at 60 RUNES (rowLabel), and this record has both " +
			"shapes that distinguish an implementation: labels over the limit that must be " +
			"cut, and one label of 47 runes / 139 bytes that must NOT be — a host limiting " +
			"bytes would truncate it, and truncating a 3-byte rune at byte 60 emits U+FFFD " +
			"where the question had a character. Every label must remain valid UTF-8 and " +
			"end in the ellipsis or not at all. Its own producing run also found a real " +
			"defect: fakeAnswer truncated the echoed statement by byte (provider/fake.go).",
		exitCode: 0,
	},
}

func TestHostCorpus(t *testing.T) {
	for _, c := range corpusCases {
		t.Run(c.name, func(t *testing.T) {
			rec := loadCorpusRecord(t, c.name)

			// The SAME fold a host gets from `quarry run --events-json`, with the same
			// arguments. A corpus built from a different call would pin a stream nothing
			// emits — the wired-seam-the-CLI-does-not-wire defect, one repo out.
			var prov *Provenance
			if p := ProvenanceOf(rec, nil); p.StabilityKnown {
				prov = &p
			}
			events := HostRunEvents(rec, "file:///testdata/"+c.name+".json", prov)

			var stream strings.Builder
			if err := WriteRunEvents(&stream, events); err != nil {
				t.Fatal(err)
			}
			exp, err := WriteExpectation(ExpectationOf(c.name, c.note, c.exitCode, events))
			if err != nil {
				t.Fatal(err)
			}

			assertCorpusFile(t, c.name+".ndjson", []byte(stream.String()))
			assertCorpusFile(t, c.name+".expected.json", exp)
		})
	}
}

// The SYNTHETIC cases (#9), which no record can produce.
//
// Three properties the corpus must pin have no record behind them: an event kind quarry
// does not emit yet, a cost that serializes without a decimal point, and a stream that
// stops mid-line. Each is a fact about the FRAMING rather than about a run, so each is
// constructed here — and constructing them is legitimate for exactly the reason CLAUDE.md
// usually warns against it: these are not states a run reaches, they are states a HOST
// will be handed, by a future quarry or by a crash.
//
// unknownKindEvent is what a MINOR version bump looks like from a host's side (D2). The
// compatibility rule says adding a kind cannot break a conforming consumer, and
// runevent.go has claimed that in a comment since the file was written with nothing
// testing it — the claim is only worth making if a stream exercising it ships.
type unknownKindEvent struct {
	Type string `json:"type"`
	// Deliberately carries a field no current kind has. A host must skip the whole object,
	// not merely tolerate a known object with an extra key.
	Detail string `json:"detail"`
}

func (unknownKindEvent) eventType() string { return "quarry_future_kind" }

// integralCostEvent is a receipt whose figures are round dollars, so they serialize as
// `1` and `2` rather than `1.000000`.
//
// A SEPARATE FIXTURE BECAUSE NO REAL RUN IS THIS EXPENSIVE. quarry's costs are fractions
// of a cent, so every other stream here happens to carry a decimal point in every cost
// field — and a host whose number parser requires one would pass the entire corpus and
// then fail on the first million-micro-unit row. It is the cheapest possible fixture for
// a defect that only appears in production.
func integralCostReceipt() ReceiptEvent {
	return ReceiptEvent{Type: "receipt", Total: 3, Rows: []ReceiptRow{
		{Label: "n0.0 a round dollar", Kind: KindLLM, Cost: 1},
		{Label: "n0.1 two round dollars", Kind: KindLLM, Cost: 2},
	}}
}

// TestSyntheticCorpusCases writes the three streams above, plus the crashed case.
func TestSyntheticCorpusCases(t *testing.T) {
	t.Run("unknown-kind", func(t *testing.T) {
		// Interleaved AMONG the known kinds, not appended after the outcome. Appended, a host
		// that stopped reading at the terminal event would skip it and pass without ever
		// exercising the tolerance; between the answer and the receipt, it has to be skipped
		// on the way to a figure the expectation checks.
		events := []RunEvent{
			StreamEvent{Type: "quarry_stream", Version: StreamVersion, Producer: "quarry-go"},
			ModelEvent{Type: "model", Tier: "m@1", Label: "m@1", State: "done", Cost: 3},
			AnswerEvent{Type: "answer", Text: "an answer, folded past a kind the reader does not know"},
			unknownKindEvent{Type: "quarry_future_kind", Detail: "a field no current kind has"},
			integralCostReceipt(),
			ArtifactEvent{Type: "artifact", RunID: "synthetic-unknown-kind", URL: "file:///testdata/synthetic.json"},
			OutcomeEvent{Type: "quarry_outcome", Outcome: OutcomeComplete, BoundBy: "",
				Gaps: 0, Unfunded: 0, TotalMicros: 3_000_000, CapMicros: 5_000_000},
		}
		var stream strings.Builder
		if err := WriteRunEvents(&stream, events); err != nil {
			t.Fatal(err)
		}
		exp := ExpectationOf("unknown-kind",
			"SYNTHETIC — hand-built, not folded from a record. An event kind quarry does not "+
				"emit, sitting BETWEEN the answer and the receipt: a host must skip the whole "+
				"object and still fold every known kind (D2's minor-bump rule, which runevent.go "+
				"asserted in a comment for a year with nothing testing it). Also the only case "+
				"whose costs are ROUND DOLLARS, so they serialize as `1` and `2` with no decimal "+
				"point — a host demanding one rejects a valid receipt, and no real quarry run is "+
				"expensive enough to catch that.",
			0, events)
		// event_types records the unknown kind by name, so the expectation says plainly that a
		// conforming host saw it and skipped it rather than that it was absent.
		b, err := WriteExpectation(exp)
		if err != nil {
			t.Fatal(err)
		}
		assertCorpusFile(t, "unknown-kind.ndjson", []byte(stream.String()))
		assertCorpusFile(t, "unknown-kind.expected.json", b)
	})

	t.Run("crashed", func(t *testing.T) {
		// A stream cut MID-LINE, which is what a killed producer leaves behind. The truncation
		// point is inside the artifact event's JSON deliberately: cutting between lines would
		// leave a well-formed NDJSON stream that merely lacks a terminal event — a weaker case,
		// and one a host might read as a clean early exit.
		//
		// This is the case that makes the terminal event load-bearing. Without it, a host has
		// no in-band way to tell this from time-truncated: both give it whole lines and an
		// answer, and only one of them finished.
		full := []RunEvent{
			StreamEvent{Type: "quarry_stream", Version: StreamVersion, Producer: "quarry-go"},
			AnswerEvent{Type: "answer", Text: "a partial run, killed before it could report an outcome"},
			// []ReceiptRow{} and NOT nil. A nil slice encodes as `"rows":null`, and RunEvents
			// never emits that — it builds rows with make(..., 0, n), so a spendless receipt is
			// always `"rows":[]` (see no-answer-spend.ndjson). A synthetic fixture showing a
			// shape quarry cannot produce would have both twins writing a null branch for a case
			// that never arrives, which is worse than no fixture: it is a fabricated requirement.
			ReceiptEvent{Type: "receipt", Rows: []ReceiptRow{}, Total: 0},
			ArtifactEvent{Type: "artifact", RunID: "synthetic-crashed", URL: "file:///testdata/synthetic.json"},
		}
		var stream strings.Builder
		if err := WriteRunEvents(&stream, full); err != nil {
			t.Fatal(err)
		}
		// Chop 12 bytes off, landing inside the artifact object and past its final newline.
		truncated := stream.String()
		truncated = truncated[:len(truncated)-12]
		if strings.HasSuffix(truncated, "\n") {
			t.Fatal("the truncation must land MID-LINE or this fixture is not a crash")
		}
		assertCorpusFile(t, "crashed.ndjson", []byte(truncated))

		// No .expected.json fold for this one — ExpectationOf takes events, and the point of
		// the case is that the bytes do not parse into a complete set. The expectation is
		// stated as an assertion here and in the README instead, which is the honest place: a
		// crashed stream has no outcome to expect.
		parsed, err := ReadStreamEvents([]byte(truncated))
		if err == nil {
			t.Fatal("a mid-line truncation must be REPORTED, not silently accepted: a host that " +
				"tolerated it would treat a killed run as a finished one")
		}
		if len(parsed) != 3 {
			t.Errorf("the complete lines before the break must still be returned, got %d of 3 — "+
				"a host should be able to say WHAT it got before the stream died", len(parsed))
		}
		if _, ok := TerminalOutcome(parsed); ok {
			t.Error("a crashed stream must have NO terminal outcome; that absence is the whole signal")
		}
	})
}

// assertCorpusFile writes the file under -update and otherwise asserts it is
// BYTE-IDENTICAL — #9's requirement, because a fixture that drifts silently is worse
// than none.
//
// The failure message names -update rather than describing the diff. A whole-file diff of
// a 25-row stream is unreadable, and the actionable question is always the same one: was
// this change intended, and if so is the twins' side updated too.
func assertCorpusFile(t *testing.T, name string, want []byte) {
	t.Helper()
	path := filepath.Join(corpusDir, name)
	if *update {
		if err := os.WriteFile(path, want, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s (%d bytes)", path, len(want))
		return
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%v\n  regenerate with: go test -run TestHostCorpus -update", err)
	}
	if string(got) != string(want) {
		t.Errorf("%s is not byte-identical to the current fold.\n"+
			"  the corpus is a CONTRACT two other repos vendor, so this is either a wire "+
			"change that needs a version bump (D2) or an accident.\n"+
			"  intended? go test -run TestHostCorpus -update — and tell bucktooth and "+
			"rustynail.\n  on disk %d bytes, folded %d bytes", name, len(got), len(want))
	}
}

func loadCorpusRecord(t *testing.T, name string) RunRecord {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(corpusDir, name+".json"))
	if err != nil {
		t.Fatal(err)
	}
	var rec RunRecord
	if err := json.Unmarshal(b, &rec); err != nil {
		t.Fatal(err)
	}
	return rec
}

// TestCorpusCoversEveryOutcome is the VACUITY GUARD on the corpus, and the reason it is a
// separate test is that its failure means something different: not "a fixture changed" but
// "the corpus no longer covers what it claims to".
//
// A corpus of six cases that all classify the same way would pass every byte-identity
// check above while testing one path. CLAUDE.md's rule — a check that claims to cover a
// specific condition must verify it reached that condition — applies to a fixture set as
// much as to a test.
func TestCorpusCoversEveryOutcome(t *testing.T) {
	seen := map[Outcome]string{}
	for _, c := range corpusCases {
		rec := loadCorpusRecord(t, c.name)
		seen[rec.Classify()] = c.name
	}
	for _, want := range []Outcome{OutcomeComplete, OutcomeTimeTruncated, OutcomeDegraded, OutcomeNoAnswer} {
		if seen[want] == "" {
			t.Errorf("no corpus case classifies as %q, so nothing pins that path", want)
		}
	}
}

// TestCorpusPinsTheCasesThatDistinguishImplementations asserts the corpus still contains
// the SPECIFIC properties each case was chosen for.
//
// WITHOUT THIS THE CORPUS DECAYS INVISIBLY. Every case above is byte-checked, so a
// replacement record that still folds deterministically passes — even if it lost the
// property that made it worth vendoring. That is precisely how #18's predecessor test went
// vacuous: it summed 1+2+3, which is exact in float64, so it passed under the defect it
// existed to catch. Same failure mode, one layer out.
func TestCorpusPinsTheCasesThatDistinguishImplementations(t *testing.T) {
	// The live record is the only case whose rows do not sum in float64. If a future edit
	// makes it reconcile naively, the corpus stops catching a host that sums floats and
	// nothing else here would notice.
	live := expectationOnDisk(t, "live-partition")
	if live.Receipt.FloatSumEqualsTotal {
		t.Error("live-partition no longer has rows that disagree with the total in float64; " +
			"the corpus has lost the property #18 exists for. replace it with a real wide run")
	}
	if live.Receipt.TotalMicros == 0 || len(live.Receipt.Rows) < 20 {
		t.Errorf("live-partition must stay a WIDE spending run (got %d rows, %d micro-units); "+
			"a narrow one cannot exhibit the accumulating float error",
			len(live.Receipt.Rows), live.Receipt.TotalMicros)
	}
	// And the model-spend residual, which is structural rather than floating-point: no
	// comparison rule reaches it, so only a fixture can tell a host it is expected.
	if live.ModelSpendUnexplainedMicros == 0 {
		t.Error("live-partition no longer shows a model-spend residual; if that was FIXED " +
			"in the executor, this expectation and the ModelEvent doc both need updating " +
			"(#20), and the twins need telling")
	}

	// Gaps and unfunded must appear SEPARATELY somewhere, or the corpus cannot show a host
	// that they are different denominations.
	timeCase := expectationOnDisk(t, "time-truncated")
	if timeCase.Gaps == 0 || timeCase.Unfunded != 0 {
		t.Errorf("time-truncated must have gaps and NO unfunded nodes, got %d/%d — "+
			"otherwise the corpus does not separate the denominations",
			timeCase.Gaps, timeCase.Unfunded)
	}
	spendCase := expectationOnDisk(t, "no-answer-spend")
	if spendCase.Unfunded == 0 || spendCase.Gaps != 0 {
		t.Errorf("no-answer-spend must have unfunded nodes and NO gaps, got %d/%d — "+
			"only TIME produces a gap (standing ruling)",
			spendCase.Unfunded, spendCase.Gaps)
	}

	// The unicode case is only useful if bytes and runes actually differ in it.
	uni := expectationOnDisk(t, "unicode")
	stream, err := os.ReadFile(filepath.Join(corpusDir, "unicode.ndjson"))
	if err != nil {
		t.Fatal(err)
	}
	if !hasMultibyte(string(stream)) {
		t.Error("unicode.ndjson contains no multi-byte rune, so it cannot distinguish a host " +
			"that counts bytes from one that counts runes")
	}
	if uni.AnswerRunes == 0 {
		t.Error("unicode case has no answer to measure")
	}

	// THE UNLIMITED CAP, asserted because the README documents -1 as a rule a host must
	// implement and a documented rule with no fixture behind it is the shape of requirement
	// that gets implemented wrong. 0 would read as a cap of nothing.
	unl := expectationOnDisk(t, "deadline-only")
	if unl.CapMicros != -1 {
		t.Errorf("deadline-only must carry cap_micros -1, got %d — if the run was recaptured "+
			"with a --cap, the corpus no longer exhibits the unlimited case at all", unl.CapMicros)
	}
	if unl.TotalMicros <= 0 {
		t.Errorf("deadline-only must have SPENT something (got %d): an unlimited cap beside a "+
			"zero total cannot distinguish -1 from 0 for a host that renders spend as a "+
			"fraction of the cap", unl.TotalMicros)
	}

	// THE TRUNCATION BOUNDARY, which the short unicode case cannot reach — its longest
	// label is 49 runes against a 60-rune limit, so it exercises multi-byte text and never
	// exercises cutting it. Both halves are asserted, and the second is the one that
	// distinguishes implementations: a label UNDER the rune limit but OVER it in bytes must
	// come through whole.
	long := expectationOnDisk(t, "unicode-long")
	var cut, wideUncut int
	for _, row := range long.Receipt.Rows {
		if !utf8.ValidString(row.Label) {
			t.Errorf("label %q is not valid UTF-8: a byte-indexed truncation split a rune, and "+
				"a host writing that to JSON emits U+FFFD where the question had a character",
				row.Label)
		}
		if strings.ContainsRune(row.Label, utf8.RuneError) {
			t.Errorf("label %q carries a replacement character, indistinguishable from the "+
				"model having produced one", row.Label)
		}
		runes := utf8.RuneCountInString(row.Label)
		switch {
		case strings.HasSuffix(row.Label, "…"):
			cut++
			// rowLabel cuts at labelStatementLimit runes and prefixes "n0.x ", so a cut label
			// is longer than the limit in runes but must not be a byte-count away from it.
			if runes > labelStatementLimit+16 {
				t.Errorf("label %q is %d runes: a cut label must be bounded in RUNES, not bytes",
					row.Label, runes)
			}
		case runes < len(row.Label):
			// Multi-byte and NOT cut, which is the case a byte limit gets wrong.
			wideUncut++
		}
	}
	if cut == 0 {
		t.Error("unicode-long has no truncated label, so it does not reach the boundary it " +
			"exists for — replace it with a run whose sub-questions exceed 60 runes")
	}
	if wideUncut == 0 {
		t.Error("unicode-long has no label that is under the RUNE limit and over it in BYTES; " +
			"without one the corpus cannot catch a host that truncates bytes, which is the " +
			"whole difference between the two implementations")
	}
}

func expectationOnDisk(t *testing.T, name string) StreamExpectation {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(corpusDir, name+".expected.json"))
	if err != nil {
		t.Fatalf("%v\n  regenerate with: go test -run TestHostCorpus -update", err)
	}
	var exp StreamExpectation
	if err := json.Unmarshal(b, &exp); err != nil {
		t.Fatal(err)
	}
	return exp
}

func hasMultibyte(s string) bool {
	for _, r := range s {
		if r > 127 {
			return true
		}
	}
	return false
}
